apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: mult-hpa
  namespace: a0008
spec:
  maxReplicas: 10
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mult-deployment
  targetCPUUtilizationPercentage: 95
