kind: Pod
apiVersion: v1
metadata:
  name: azure-cli-pod
  namespace: a0008
  labels:
    aadpodidbinding: podmi-ingress-controller
spec:
  containers:
    - name: azure-cli-container
      image: mcr.microsoft.com/azure-cli
      imagePullPolicy: Always
      securityContext:
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: false
        capabilities:
          drop:
            - all
      resources:
        requests:
          cpu: 50m
          memory: 128Mi
        limits:
          cpu: 200m
          memory: 256Mi
      command:
        - "/bin/sleep"
        - "10000"
      volumeMounts:
      - name: secrets-store-volume
        mountPath: "/mnt/secrets-store"
        readOnly: true
  volumes:
    - name: secrets-store-volume
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: "my-demo-secret-csi-akv--fs"