apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: my-demo-secret-csi-akv--env-var
  namespace: a0008
spec:
  provider: azure
  parameters:
    usePodIdentity: "true"
    keyvaultName: <key-vault-name>
    objects:  |
      array:
        - |
          objectName: my-demo-secret
          objectType: secret
    tenantId: <tenant-Id>
  secretObjects:                             
  - secretName: my-demo-secret-object   
    data:
    - key: my-demo-secret-key                          
      objectName: my-demo-secret                                        
    type: Opaque   