apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: my-demo-secret-csi-akv--fs
  namespace: a0008
spec:
  provider: azure
  parameters:
    usePodIdentity: "true"
    keyvaultName: <key-vault-name>
    objects:  |
      array:
        - |
          objectName: my-demo-secret
          objectType: secret
    tenantId: <tenant-Id>